### ISSUE TITLE
Report dead links?

### ISSUE THREAD

**Issue by bakgatviooldoos** [soegaard/racket-stories#20]
Hi, @soegaard.

Thanks for this site; a wonderful resource. I am just browsing at the moment, but I visited a link to a site which no longer exists/resides in the original location. Would it be helpful if there was a mechanism to report these links, or to "tag" them as such?

The link in question: https://gopiandcode.uk/logs/log-racket-and-rhombus-sexp.html.

**Comment by soegaard** [comment]
Thanks for noticing.

> Would it be helpful if there was a mechanism to report these links, or to "tag" them as such?

It would - but making an issue here is also fine.
Fixing this in my database tool is straight forward.

This is the first broken link (I have heard about) so far.
I have contacted Kiran to hear whether the blog post 
was moved on purpose or not.

**Comment by soegaard** [comment]
I have updated the link at Racket Stories.

https://kirancodes.me/logs/log-racket-and-rhombus-sexp.html

**Comment by bakgatviooldoos** [comment]
Thanks, @soegaard. Doing the lord's work.
